apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-ml
spec:
  selector:
    matchLabels:
      app: flask-ml
  replicas: 2
  template:
    metadata:
      labels:
        app: flask-ml
    spec:
      containers:
      - name: flask-ml
        image: dyzhou66/flask-ml:latest
        ports:
        - containerPort: 8080
        resources:
          requests:
            memory: "500Mi"
            cpu: "250m"
          limits:
            memory: "1000Mi"
            cpu: "500m"

---
apiVersion: v1
kind: Service
metadata:
  name: flask
spec:
  type: NodePort
  selector:
    app: flask-ml
  ports:
    - port: 8080
      targetPort: 8080
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: main-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$1
spec:
  rules:
    - host: "myGDdemo.com"
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: flask-ml
                port:
                  number: 8080